export const MENU_ITEMS = [
  {
    id: 1,
    name: "Espresso",
    description: "Strong and bold shot of pure coffee.",
    price: 2.5,
    size: ["single", "double"],
    category: "Hot Coffee",
  },
  {
    id: 2,
    name: "Americano",
    description: "Espresso diluted with hot water.",
    price: 3.0,
    size: ["small", "medium", "large"],
    category: "Hot Coffee",
  },
  {
    id: 3,
    name: "Cappuccino",
    description: "Espresso with steamed milk and foam.",
    price: 3.5,
    size: ["small", "medium", "large"],
    category: "Hot Coffee",
  },
  {
    id: 4,
    name: "Latte",
    description: "Espresso with steamed milk, lightly topped with foam.",
    price: 4.0,
    size: ["small", "medium", "large"],
    category: "Hot Coffee",
  },
  {
    id: 5,
    name: "Mocha",
    description: "Espresso with chocolate, steamed milk, and whipped cream.",
    price: 4.5,
    size: ["small", "medium", "large"],
    category: "Hot Coffee",
  },
  {
    id: 6,
    name: "Iced Coffee",
    description: "Chilled brewed coffee served over ice.",
    price: 3.5,
    size: ["medium", "large"],
    category: "Cold Coffee",
  },
  {
    id: 7,
    name: "Iced Latte",
    description: "Espresso with cold milk, served over ice.",
    price: 4.0,
    size: ["medium", "large"],
    category: "Cold Coffee",
  },
  {
    id: 8,
    name: "Frappuccino",
    description: "Blended iced coffee with milk and flavored syrup.",
    price: 4.75,
    size: ["medium", "large"],
    category: "Cold Coffee",
  },
  {
    id: 9,
    name: "Cold Brew",
    description: "Slow-steeped cold brew coffee, smooth and bold.",
    price: 4.25,
    size: ["medium", "large"],
    category: "Cold Coffee",
  },
  {
    id: 10,
    name: "Cold Mocha",
    description: "Espresso with cold milk, served over ice.",
    price: 4.25,
    size: ["medium", "large"],
    category: "Cold Coffee",
  },
];
